#CONF EUREKA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090
  
spring:
  application:
    name: zuul-server
    
zuul:
  routes:
    productos:
      service-id: servicio-productos
      path: /api/productos/**
    item:
      service-id: servicio-item
      path: /api/items/**
      
  host:
    connect-timeout-millis: 10000
    
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 15000
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000