#SPRING CONFIG
spring:
  application:
    name: zuul-server

#EUREKA CONFIG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#ZUUL CONFIG  
zuul:
  routes:
    productos:
      service-id: servicio-productos
      path: /api/productos/**
    item:
      service-id: servicio-item
      path: /api/items/**
    usuarios:
      service-id: servicio-usuarios
      path: /api/admin/**
  host:
    connect-timeout-millis: 10000
  
#HYSTRIX CONFIG
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 15000

#RIBBON CONFIG
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000
  
#SERVER CONFIG
server:
  port: 8090